import json
import os

new_idioms = [
    {"idiom": "అగ్నికి వాయువు తోడైనట్లు (Agniki vayuvu thodainatlu)", "literal_meaning": "Wind joining the fire.", "figurative_meaning": "A bad situation becoming worse due to an external factor.", "example": "Vaadi kopaniki nee maatalu agniki vayuvu thodainatlu ayyayi.", "language": "Telugu"},
    {"idiom": "ఎలుకకు పిల్లి సాక్షి (Elukaku pilli sakshi)", "literal_meaning": "A cat standing as witness for a rat.", "figurative_meaning": "An untrustworthy or compromised witness; a conflict of interest.", "example": "Donga ki inko donga support cheyadam elukaku pilli sakshi lanti de.", "language": "Telugu"},
    {"idiom": "కీలెరిగి వాత పెట్టాలి (Keelerigi vatha pettali)", "literal_meaning": "Find the joint and apply the brand.", "figurative_meaning": "Speak or act precisely where it hurts or matters the most.", "example": "Vaadi weakness thelusukuni keelerigi vatha pettadu.", "language": "Telugu"},
    {"idiom": "గొంగళిలో తింటూ వెంట్రుకలు ఏరుకున్నట్లు (Gongalilo thintu ventrukalu eerukunnatlu)", "literal_meaning": "Eating from a wool blanket and picking out hairs.", "figurative_meaning": "Complaining about inevitable minor flaws in a situation.", "example": "Chinna thappulanu pattinchukoku, gongalilo thintu ventrukalu eerukunnatlu avuthundi.", "language": "Telugu"},
    {"idiom": "గుడ్డి ఎద్దు జొన్న చేలో పడ్డట్టు (Guddi eddu jonna chelo paddattu)", "literal_meaning": "A blind ox falling into a cornfield.", "figurative_meaning": "Doing things haphazardly and blindly ruining everything without direction.", "example": "Vaadiki em theliyakunda paninatha paduchesadu, guddi eddu jonna chelo paddattu.", "language": "Telugu"},
    {"idiom": "తీయగా తీయగా రాగం, మూలగగా మూలగగా రోగం (Theeyaga theeyaga raagam, moolagaga moolagaga rogam)", "literal_meaning": "Singing makes a tune sweet, groaning makes sickness worse.", "figurative_meaning": "Practice makes perfect, but constant complaining breeds negativity.", "example": "Eppudu edavaku, theeyaga theeyaga raagam moolagaga moolagaga rogam.", "language": "Telugu"},
    {"idiom": "మింగలేక కక్కలేక (Mingaleeka kakkaleeka)", "literal_meaning": "Unable to swallow, unable to vomit.", "figurative_meaning": "Being caught in an extremely difficult dilemma.", "example": "Aa kothha rules tho staff mingaleeka kakkaleeka avastha paduthunnaru.", "language": "Telugu"},
    {"idiom": "ముందొచ్చిన చెవుల కన్నా వెనకొచ్చిన కొమ్ములు వాడి (Mundochina chevula kanna venakochina kommulu vaadi)", "literal_meaning": "Horns that came later are sharper than the ears that came first.", "figurative_meaning": "Newcomers or juniors outshining the seniors.", "example": "Kothaga vachina kurradu senior kante baaga chestunnadu, mundochina chevula kanna venakochina kommulu vaadi.", "language": "Telugu"},
    {"idiom": "రొంపిలో పడ్డ పంది లాగా (Rompilo padda pandi laaga)", "literal_meaning": "Like a pig stuck in mud.", "figurative_meaning": "A person who is stuck in a messy situation and cannot escape.", "example": "Appula baadhaltho rompilo padda pandi laaga thayarayyadu.", "language": "Telugu"},
    {"idiom": "పుండు మీద కారం చల్లినట్లు (Pundu meeda kaaram challinatlu)", "literal_meaning": "Sprinkling chili powder on a wound.", "figurative_meaning": "Adding insult to injury.", "example": "Akkade badhalo unte nuvvu velli inka edipinchadam pundu meeda kaaram challinatlu.", "language": "Telugu"},
    {"idiom": "ఆకలి రుచి ఎరుగదు, నిద్ర సుఖమెరుగదు (Aakali ruchi erugadu, nidra sukhamerugadu)", "literal_meaning": "Hunger knows no taste, sleep knows no comfort.", "figurative_meaning": "When completely exhausted or starving, quality doesn't matter.", "example": "Rendu rojulu nunchi nidra ledu, aakali ruchi erugadu nidra sukhamerugadu.", "language": "Telugu"},
    {"idiom": "ఆవు వ్యాకరణం చదివినట్లు (Aavu vyakaranam chadinatlu)", "literal_meaning": "Like a cow studying grammar.", "figurative_meaning": "Doing something completely out of one's depth or comprehension.", "example": "Vaadiki science theliyadu, technical ga matladatam aavu vyakaranam chadinatlu.", "language": "Telugu"},
    {"idiom": "ఉన్న మాట చెబితే ఉలుకెక్కువ (Unna maata chebithe ulukekkuva)", "literal_meaning": "Speaking the truth causes more irritation.", "figurative_meaning": "People get angry when confronted with the bitter truth.", "example": "Nenu nijam chebithe neeku kopam enduku, unna maata chebithe ulukekkuva.", "language": "Telugu"},
    {"idiom": "ఎక్కడ వేసిన గొంగళి అక్కడే ఉన్నట్లు (Ekkada vesina gongali akkade unnatlu)", "literal_meaning": "The blanket remaining exactly where it was thrown.", "figurative_meaning": "Zero progress made in a task over a long period of time.", "example": "One year nunchi work chestunnam gani ekkada vesina gongali akkade unnatlu undi.", "language": "Telugu"},
    {"idiom": "ఏరు దాటాక బోడి మల్లన్న (Eru daataka bodi mallanna)", "literal_meaning": "Calling the boatman 'bald Mallanna' after crossing the river.", "figurative_meaning": "Being extremely ungrateful once a favor is received.", "example": "Sahayam theesukoni ippudu nannu thidutunnava, eru daataka bodi mallanna.", "language": "Telugu"},
    {"idiom": "కడుపు చించుకుంటే కాళ్ళ మీద పడుతుంది (Kadupu chinchukunte kalla meeda paduthundi)", "literal_meaning": "Tearing your own stomach drops things on your feet.", "figurative_meaning": "Washing dirty linen in public only brings shame to your own family.", "example": "Family godavalu bayata cheppaku, kadupu chinchukunte kalla meeda paduthundi.", "language": "Telugu"},
    {"idiom": "కుక్కను తెచ్చి సింహాసనం మీద కూర్చోబెట్టినట్లు (Kukkanu thechi simhasanam meeda kurchobettinatlu)", "literal_meaning": "Bringing a dog and making it sit on a throne.", "figurative_meaning": "Elevating an undeserving, ill-mannered person to a high position.", "example": "Vaadiki promotion ivvadam kukkanu thechi simhasanam meeda kurchobettinatlu.", "language": "Telugu"},
    {"idiom": "కూటికి గతి లేదు, కులమెక్కువ (Kootiki gathi ledu, kulamekkuva)", "literal_meaning": "No food to eat, but boastful of high caste.", "figurative_meaning": "Having no actual wealth or success, but showing off false pride.", "example": "Appulu chesi karchu chestunnadu, kootiki gathi ledu kulamekkuva.", "language": "Telugu"},
    {"idiom": "గుడిని, గుడిలో లింగాన్ని మింగే రకం (Gudini, gudilo linganni minge rakam)", "literal_meaning": "The type to swallow the temple and the idol inside.", "figurative_meaning": "An extremely corrupt and greedy person.", "example": "Aa politician ni nammaku, gudini gudilo linganni minge rakam.", "language": "Telugu"},
    {"idiom": "చెట్టు పేరు చెప్పి కాయలు అమ్మినట్లు (Chettu peru cheppi kayalu amminatlu)", "literal_meaning": "Selling fruits by taking the name of the tree.", "figurative_meaning": "Using someone else's famous name or brand to benefit yourself.", "example": "Vaadu nanna peru cheppukoni brathukestunnadu, chettu peru cheppi kayalu amminatlu.", "language": "Telugu"},
    {"idiom": "చేతికి ఎముక లేదు (Chethiki emuka ledu)", "literal_meaning": "No bone in the hand.", "figurative_meaning": "Being extremely generous and giving freely.", "example": "Aayana dhanam ivvadamlo chethiki emuka ledu.", "language": "Telugu"},
    {"idiom": "తడి గుడ్డతో గొంతు కోయడం (Thadi guddatho gonthu koyadam)", "literal_meaning": "Cutting a throat with a wet cloth.", "figurative_meaning": "Betraying someone slowly and sweetly from the inside.", "example": "Nuvvu friend ani nammithe thadi guddatho gonthu kosavu.", "language": "Telugu"},
    {"idiom": "తలలు బోడులైనా తలపులు బోడులా (Thalalu bodulaina thalapulu bodulaa)", "literal_meaning": "Even if heads are bald, are thoughts bald?", "figurative_meaning": "Outward simplicity doesn't mean a lack of intelligence or complex thoughts.", "example": "Sanyasi ani theesipareyaku, thalalu bodulaina thalapulu bodulaa.", "language": "Telugu"},
    {"idiom": "తాడెత్తు ఎదిగినా బుద్ధెత్తు లేదు (Thaadetthu edigina buddhetthu ledu)", "literal_meaning": "Grew as tall as a palm tree but no brain at all.", "figurative_meaning": "Physical growth without corresponding mental maturity.", "example": "Entha peddavadaivyo gani thaadetthu edigina buddhetthu ledu.", "language": "Telugu"},
    {"idiom": "నక్క ఎక్కడ, నాగలోకం ఎక్కడ (Nakka ekkada, nagalokam ekkada)", "literal_meaning": "Where is the fox, and where is heaven?", "figurative_meaning": "A mismatch of monumental proportions; comparing the lowest to the highest.", "example": "Vaaditho nannu compare cheyaku, nakka ekkada nagalokam ekkada.", "language": "Telugu"},
    {"idiom": "నీటిలో మొసలి ఏనుగును పట్టుకుంటుంది (Neetilo mosali enugunu pattukuntundi)", "literal_meaning": "In water, a crocodile can catch an elephant.", "figurative_meaning": "Everyone is powerful on their home turf.", "example": "Vaadi area lo vaade king, neetilo mosali enugunu pattukuntundi kadha.", "language": "Telugu"},
    {"idiom": "నోటితో నవ్వి నొసటితో వెక్కిరించినట్లు (Notitho navvi nosatitho vekkirinchinatlu)", "literal_meaning": "Smiling with the mouth, mocking with the forehead.", "figurative_meaning": "Being two-faced or hypocritical.", "example": "Vaadu bayataki friend kani notitho navvi nosatitho vekkirinchinatlu chestadu.", "language": "Telugu"},
    {"idiom": "పండిత పుత్ర శుంఠ (Pandita putra shuntha)", "literal_meaning": "The son of a scholar is a dunce.", "figurative_meaning": "Genius is not always inherited.", "example": "Aayana entho goppa scientist kani vaadi koduku pandita putra shuntha.", "language": "Telugu"},
    {"idiom": "పాలు తాగి రొమ్ము గుద్దినట్లు (Paalu thaagi rommu gudhinatlu)", "literal_meaning": "Drinking milk and punching the breast.", "figurative_meaning": "Biting the hand that feeds you.", "example": "Company nunchi anni theesukoni vallane mosam chesadu, paalu thaagi rommu gudhinatlu.", "language": "Telugu"},
    {"idiom": "పెళ్లికి వెళ్తూ పిల్లిని చంకలో పెట్టుకెళ్ళినట్లు (Pelliki velthu pillini chankalo pettukellinatlu)", "literal_meaning": "Carrying a cat in the armpit while going to a wedding.", "figurative_meaning": "Carrying unnecessary trouble to an auspicious or good event.", "example": "Akkada antha manchiga jaruguthunte ee issue thesthaventi, pelliki velthu pillini chankalo pettukellinatlu.", "language": "Telugu"},
    {"idiom": "మసి పూసి మారేడు కాయ చేసినట్లు (Masi poosi maredu kaya chesinatlu)", "literal_meaning": "Smearing ash and passing it off as a bael fruit.", "figurative_meaning": "Creating a fraudulent disguise or deceiving cleverly.", "example": "Pazhaya bandi ki masi poosi maredu kaya chesinatlu ammesadu.", "language": "Telugu"},
    {"idiom": "రాజు తలుచుకుంటే దెబ్బలకు కొదవా (Raju thaluchukunte debbalaku kodavaa)", "literal_meaning": "If the king wills it, is there a shortage of beatings?", "figurative_meaning": "Absolute power dictates consequences effortlessly.", "example": "Boss anukunte nuvvu fire avvadaniki entha sepu, raju thaluchukunte debbalaku kodavaa.", "language": "Telugu"},
    {"idiom": "రోకలికి చిగురు పుట్టినట్లు (Rokaliki chiguru puttinatlu)", "literal_meaning": "Like a wooden pestle sprouting leaves.", "figurative_meaning": "An absolutely impossible event.", "example": "Vaadu exam pass ayyada? Rokaliki chiguru puttinatlu undi.", "language": "Telugu"},
    {"idiom": "వయసొస్తే వంకర కర్ర కూడా అందంగా ఉంటుంది (Vayasoste vankara karra kuda andanga untundi)", "literal_meaning": "In youth, even a crooked stick looks beautiful.", "figurative_meaning": "Youth imparts an automatic illusion of beauty.", "example": "Pellidu vachaka evaraina andanga kanipistharu, vayasoste vankara karra kuda andanga untundi.", "language": "Telugu"},
    {"idiom": "వినేవాడు వెర్రివాడైతే, చెప్పేవాడు శివతత్వం చెప్పాడట (Vinevaadu verrivaadaithe, cheppevaadu shivatathvam cheppadata)", "literal_meaning": "If the listener is a fool, the speaker claims to speak divine philosophy.", "figurative_meaning": "Exploiting the ignorance of the audience with grand lies.", "example": "Vaadu cheppevaanni nammuthunnaru, vinevaadu verrivaadaithe cheppevaadu shivatathvam cheppadata.", "language": "Telugu"},
    {"idiom": "శనగలు తింటూ శంఖం ఊదినట్లు (Sanagalu thintu shankham oodinatlu)", "literal_meaning": "Eating chickpeas while blowing a conch.", "figurative_meaning": "Trying to do two incompatible things at once and failing at both.", "example": "Rendu full-time jobs okesari cheyalem, sanagalu thintu shankham oodinatlu avuthundi.", "language": "Telugu"},
    {"idiom": "సగం చదువు, సగం వైద్యం ప్రమాదకరం (Sagam chaduvu, sagam vaidyam pramadaakaram)", "literal_meaning": "Half knowledge and half medicine are dangerous.", "figurative_meaning": "Incomplete knowledge is worse than total ignorance.", "example": "Sagam thelusukoni expert laga matladaku, sagam chaduvu sagam vaidyam pramadaakaram.", "language": "Telugu"},
    {"idiom": "సూది కోసం సోమవారం, దారం కోసం మంగళవారం (Soodi kosam somavaram, daaram kosam mangalavaram)", "literal_meaning": "Monday for a needle, Tuesday for thread.", "figurative_meaning": "Extreme laziness or procrastination.", "example": "Oka chinna pani cheyadaniki intha thiruguthunnava, soodi kosam somavaram daaram kosam mangalavaram laaga.", "language": "Telugu"},
    {"idiom": "హంస నడక రాక, తన నడక మర్చిపోయినట్లు (Hamsa nadaka raaka, thana nadaka marchipoyinatlu)", "literal_meaning": "Failing to learn the swan's walk, and forgetting one's own.", "figurative_meaning": "Losing your originality while trying to imitate someone else.", "example": "English accent try chesi sontha bhasha marchipoyadu, hamsa nadaka raaka thana nadaka marchipoyinatlu.", "language": "Telugu"},
    {"idiom": "చేతిలో చిల్లిగవ్వ లేదు, చంకలో జమిందారీ (Chethilo chilligavva ledu, chankalo jamindaari)", "literal_meaning": "Not a penny in hand, but the attitude of a landlord.", "figurative_meaning": "Being broke but putting on wealthy airs.", "example": "Bike ki petrol ledu gani Apple watch kavali, chethilo chilligavva ledu chankalo jamindaari.", "language": "Telugu"},
    {"idiom": "కోతికి కొబ్బరికాయ ఇచ్చినట్లు (Kothiki kobbarikaya ichinatlu)", "literal_meaning": "Giving a coconut to a monkey.", "figurative_meaning": "Giving something valuable to someone who doesn't know how to use it.", "example": "Vaadiki kothha phone isthe break chesadu, kothiki kobbarikaya ichinatlu.", "language": "Telugu"},
    {"idiom": "గతం గతః (Gatham gathaha)", "literal_meaning": "The past is past.", "figurative_meaning": "Let bygones be bygones; don't dwell on the past.", "example": "Jarigindedo jarigipoyindi, gatham gathaha anukoni munduku vellu.", "language": "Telugu"},
    {"idiom": "ముందు నుయ్యి, వెనుక గొయ్యి (Mundu nuyyi, venuka goyyi)", "literal_meaning": "A well in front, a ditch behind.", "figurative_meaning": "Caught between the devil and the deep blue sea.", "example": "Ippudu job quit cheyalenu, ala ani continue avvalenu, mundu nuyyi venuka goyyi la undi.", "language": "Telugu"}
]

file_path = 'data/raw/telugu.json'
data = []
if os.path.exists(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            data = json.load(f)
        except:
            pass

existing = {item['idiom'].split(' (')[0].strip() for item in data if 'idiom' in item}
filtered = [item for item in new_idioms if item['idiom'].split(' (')[0].strip() not in existing]

data.extend(filtered)

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Added {len(filtered)} new unique idioms to telugu.json! Total is now {len(data)}.")
