import json
import os

new_idioms = [
    # Batch 2 Idioms
    {"idiom": "എലിയെ പേടിച്ച് ഇല്ലം ചുടുക (Eliye pedichu illam chuduka)", "literal_meaning": "Burning the house out of fear of a rat.", "figurative_meaning": "Taking an extreme or destructive measure to solve a small problem.", "example": "Cheruthaaya problem solve cheyyan company thanne adaikkunnathu eliye pedichu illam chudunnathu poleyanu.", "language": "Malayalam"},
    {"idiom": "ഓടുന്ന നായയ്ക്ക് ഒരു മുഴം മുമ്പേ (Odunna naayakku oru muzham mumpe)", "literal_meaning": "Throwing the stick a yard ahead of the running dog.", "figurative_meaning": "Being highly proactive; anticipating actions before they happen.", "example": "Market maarunnathinu munpe avar product maatti, odunna naayakku oru muzham mumpe.", "language": "Malayalam"},
    {"idiom": "കരിമ്പു കാട്ടിൽ ആന കയറിയതു പോലെ (Karimbu kattil aana kayariyathu pole)", "literal_meaning": "Like an elephant entering a sugarcane field.", "figurative_meaning": "Being in a state of absolute joy with unlimited access to what one loves.", "example": "Sweets shopil kayariya kuttiye kandal karimbu kattil aana kayariyathu poleyanu.", "language": "Malayalam"},
    {"idiom": "പട്ടി കുരച്ചാൽ പല്ലക്ക് നിൽക്കുമോ (Patti kurachal pallakku nilkkumo)", "literal_meaning": "Will the palanquin stop if a dog barks?", "figurative_meaning": "The progress of the great will not be stopped by the criticism of the insignificant.", "example": "Avarude parihasangal kettu nee pinmaranda, patti kurachal pallakku nilkkumo.", "language": "Malayalam"},
    {"idiom": "കുറുക്കന്റെ കണ്ണ് കോഴിക്കൂട്ടിൽ (Kurukkante kannu kozhikkoottil)", "literal_meaning": "The fox's eyes are always on the chicken coop.", "figurative_meaning": "A person with ulterior motives always focuses on their target.", "example": "Avan nallathu parayunnundengilum kurukkante kannu kozhikkoottil aanu.", "language": "Malayalam"},
    {"idiom": "തലയിരിക്കുമ്പോൾ വാലാടരുത് (Thalayirikkumbol vaaladaruthu)", "literal_meaning": "The tail shouldn't wag when the head is present.", "figurative_meaning": "Subordinates should not overstep when the leader is present.", "example": "MD ivide ullappol nee theerumanam edukkaruthu, thalayirikkumbol vaaladaruthu.", "language": "Malayalam"},
    {"idiom": "പാല് കുടിച്ച പാമ്പും കടിക്കും (Paalu kudicha paambum kadikkum)", "literal_meaning": "Even a snake fed with milk will bite.", "figurative_meaning": "A wicked person will betray you even if you treat them well.", "example": "Avanodu nannayi perumariyittum chathichu, paalu kudicha paambum kadikkum.", "language": "Malayalam"},
    {"idiom": "മീൻ കുഞ്ഞിനെ നീന്താൻ പഠിപ്പിക്കണോ (Meen kunjine neenthan padippikkano)", "literal_meaning": "Do you need to teach a baby fish how to swim?", "figurative_meaning": "You don't need to teach someone what they are naturally talented at.", "example": "Avanu coding ariyamo ennu chodhikkanda, meen kunjine neenthan padippikkano.", "language": "Malayalam"},
    {"idiom": "ഒരുമയുണ്ടെങ്കിൽ ഉലക്കമേലും കിടക്കാം (Orumayundengil ulakkamelum kidakkam)", "literal_meaning": "If there is unity, you can sleep even on a pestle.", "figurative_meaning": "Any difficult situation is manageable if people stand united.", "example": "Ee prathisandhiyil namukku orumichu nilkkam, orumayundengil ulakkamelum kidakkam.", "language": "Malayalam"},
    {"idiom": "മുങ്ങിച്ചാവാൻ പോകുന്നവൻ കച്ചിത്തുരുമ്പും പിടിക്കും (Mungichavan pokunnavan kachithurumbum pidikkum)", "literal_meaning": "A drowning man will catch even a straw.", "figurative_meaning": "A desperate person will try any small chance to save themselves.", "example": "Avan last chanceum upayogichu, mungichavan pokunnavan kachithurumbum pidikkum.", "language": "Malayalam"},
    {"idiom": "കാക്ക മലർന്നു പറക്കുമോ (Kaakka malarnnu parakkumo)", "literal_meaning": "Will a crow fly upside down?", "figurative_meaning": "Something that is completely impossible.", "example": "Avan enne sahayikkum ennu ne karuthunnuvo, kaakka malarnnu parakkumo?", "language": "Malayalam"},
    {"idiom": "ഉപ്പു തിന്നവൻ വെള്ളം കുടിക്കും (Uppu thinnavan vellam kudikkum)", "literal_meaning": "He who eats salt will drink water.", "figurative_meaning": "You will have to face the consequences of your wrong actions.", "example": "Thettu cheythathu pidikkappettu, uppu thinnavan vellam kudikkum.", "language": "Malayalam"},
    {"idiom": "അണ്ണാറക്കണ്ണനും തന്നാലായത് (Annarakkannanum thannalayathu)", "literal_meaning": "Even a squirrel does what it can.", "figurative_meaning": "Every small contribution matters.", "example": "Enikondu aavunna sahayam njan cheythu, annarakkannanum thannalayathu.", "language": "Malayalam"},
    {"idiom": "വേരറുത്ത മരം പോലെ (Verarutha maram pole)", "literal_meaning": "Like a tree with its roots cut.", "figurative_meaning": "Completely helpless and falling.", "example": "Swaytham business pottiyappol avan verarutha maram pole aayi.", "language": "Malayalam"},
    {"idiom": "മുള്ളു കൊണ്ടു മുള്ളെടുക്കണം (Mullu kondu mulledukkanam)", "literal_meaning": "Remove a thorn using another thorn.", "figurative_meaning": "Fight fire with fire; use a bad thing to cure another bad thing.", "example": "Avanude kallatharam kandupidikkan mullu kondu mulledukkanam.", "language": "Malayalam"},
    {"idiom": "കാറ്റുളളപ്പോൾ പാറ്റണം (Kattullappol pattanam)", "literal_meaning": "Winnow when the wind blows.", "figurative_meaning": "Make hay while the sun shines; seize the opportunity.", "example": "Avasaram ullappol thanne muthalakkuka, kattullappol pattanam.", "language": "Malayalam"},
    {"idiom": "ആശാന് അടുപ്പിലും ആവാം (Aashaanu aduppilum aavam)", "literal_meaning": "The master can even do it in the stove.", "figurative_meaning": "Experts or masters are granted exceptions to the rules.", "example": "Avar rules thettichalum aarum onnum parayilla, aashaanu aduppilum aavam.", "language": "Malayalam"},
    {"idiom": "തിളച്ച വെള്ളത്തിൽ വീണ പൂച്ച പച്ചവെള്ളം കണ്ടാലും പേടിക്കും (Thilacha vellathil veena poocha pachavellam kandalum pedikkum)", "literal_meaning": "A cat that fell in boiling water will fear even cold water.", "figurative_meaning": "Once bitten, twice shy.", "example": "Pazhaya experience kaaranam avan onninum thuniyunnilla, thilacha vellathil veena poocha pole.", "language": "Malayalam"},
    {"idiom": "നനഞ്ഞെടം കുഴിക്കുക (Nananjedam kuzhikkuka)", "literal_meaning": "Digging where it is wet.", "figurative_meaning": "Taking the easy way out; exploiting a vulnerable person.", "example": "Avan ellavarudeyum weakness muthaledukkum, nananjedam kuzhikkuka aanu pathivu.", "language": "Malayalam"},
    {"idiom": "പൊന്നുരുക്കുന്നിടത്ത് പൂച്ചക്കെന്തു കാര്യം (Ponnurukkunnidathu poochakkenthu karyam)", "literal_meaning": "What business does a cat have where gold is melted?", "figurative_meaning": "What business does an ignorant/irrelevant person have in serious matters?", "example": "Valiyavarude meeingil nee enthina varunne, ponnurukkunnidathu poochakkenthu karyam.", "language": "Malayalam"},
    {"idiom": "വാളെടുക്കുന്നവൻ വാളാൽ (Valedukkunnavan valal)", "literal_meaning": "He who lives by the sword dies by the sword.", "figurative_meaning": "Those who commit violence will eventually suffer from it.", "example": "Don aayirunnavan adhe vazhiyil marihcu, valedukkunnavan valal.", "language": "Malayalam"},
    {"idiom": "ശ്വാനന്റെ വാല് പന്തീരാണ്ട് കുഴലിലിട്ടാലും വളഞ്ഞു തന്നെ (Shwanante vaalu pantheerandu kuzhalilittalum valanju thanne)", "literal_meaning": "A dog's tail put in a pipe for 12 years remains crooked.", "figurative_meaning": "You cannot change the fundamental bad nature of a person.", "example": "Avanu ethra upadesham koduthalum maarilla, shwanante vaalu kuzhalilittathu pole.", "language": "Malayalam"},
    {"idiom": "ചക്കിക്കൊത്ത ചങ്കരൻ (Chakkikkotha Chankaran)", "literal_meaning": "Chankaran is the perfect match for Chakki.", "figurative_meaning": "Made for each other, usually used for two similarly flawed people.", "example": "Avar randum kudi orumichu thettukal cheyyunnu, chakkikkotha chankaran.", "language": "Malayalam"},
    {"idiom": "ഇരുന്നിട്ടു വേണം കാലു നീട്ടാൻ (Irunnittu venam kaalu neettan)", "literal_meaning": "Sit first before stretching your legs.", "figurative_meaning": "Secure your position before demanding more or acting arrogant.", "example": "Job sthiramavunnathinu munpe avarodu demand cheyyaruthu, irunnittu venam kaalu neettan.", "language": "Malayalam"},
    {"idiom": "കുളക്കോഴിക്ക് എന്ത് കുളിക്കടവ് (Kulakkozhikku enthu kulikkadavu)", "literal_meaning": "What is a bathing step to a water hen?", "figurative_meaning": "A person who is always wandering has no fixed home or boundaries.", "example": "Nirantharam yathra cheyyunna avanu sthiramayi oridathu nilkkan aavilla, kulakkozhikku enthu kulikkadavu.", "language": "Malayalam"},
    {"idiom": "വെളുക്കാൻ തേച്ചത് പാണ്ടായി (Velukkan thechathu paandaayi)", "literal_meaning": "An attempt to beautify resulted in vitiligo.", "figurative_meaning": "An attempt to improve a situation made it disastrously worse.", "example": "System nannakkan sramichathu aake crash aayi, velukkan thechathu paandaayi.", "language": "Malayalam"},
    {"idiom": "അൽപ്പന് അർത്ഥം കിട്ടിയാൽ അർദ്ധരാത്രിക്ക് കുട പിടിക്കും (Alpanu artham kittiyal ardharathrikku kuda pidikkum)", "literal_meaning": "If a mean person gets wealth, he will hold an umbrella at midnight.", "figurative_meaning": "When an undeserving person gets sudden wealth, they show off foolishly.", "example": "Lottery adichappol avante ahankaram kandille, alpanu artham kittiyal ardharathrikku kuda pidikkum.", "language": "Malayalam"},
    {"idiom": "ഉറുമ്പിനും തന്റെ ജീവൻ വലുതാണ് (Urumbinum thante jeevan valuthaanu)", "literal_meaning": "Even an ant values its life.", "figurative_meaning": "Every living being values its own existence, no matter how small.", "example": "Aareyum drohikkaruthu, urumbinum thante jeevan valuthaanu.", "language": "Malayalam"},
    {"idiom": "ചുട്ടു തിന്നാലും വാസന പോവില്ല (Chuttu thinnalum vaasana povilla)", "literal_meaning": "Even if roasted, the smell won't go.", "figurative_meaning": "Deep-rooted bad habits cannot be eradicated easily.", "example": "Avanude kalla swabhavam maarilla, chuttu thinnalum vaasana povilla.", "language": "Malayalam"},
    {"idiom": "പുര കത്തുമ്പോൾ വാഴ വെട്ടുക (Pura kathumbol vazha vettuka)", "literal_meaning": "Cutting the banana tree while the house is burning.", "figurative_meaning": "Selfishly taking advantage of someone else's disaster.", "example": "Nattil prashnam nadakkumbol avar swantham karyam nokkunnu, pura kathumbol vazha vettukayanu.", "language": "Malayalam"},
    {"idiom": "അടി തെറ്റിയാൽ ആനയും വീഴും (Adi thettiyaal aaneyum veezhum)", "literal_meaning": "Even an elephant will fall if it takes a wrong step.", "figurative_meaning": "Even the strongest or most experienced person can fail if they are careless.", "example": "Avan ethra valiya expert aayalum sradhikkanam, adi thettiyal aaneyum veezhum.", "language": "Malayalam"},
    {"idiom": "അക്കരെ നിൽക്കുമ്പോൾ ഇക്കരെ പച്ച (Akkare nilkkumpol ikkare pacha)", "literal_meaning": "Things look green on this shore from the other shore.", "figurative_meaning": "The grass is always greener on the other side.", "example": "Avanu purathu pokan ishtamanu, pakshe akkare nilkkumpol ikkare pacha aanu.", "language": "Malayalam"},
    {"idiom": "അനുഭവം ആണ് മഹാ ഗുരു (Anubhavam aanu mahaa guru)", "literal_meaning": "Experience is the great teacher.", "figurative_meaning": "You learn the best lessons from your own experiences.", "example": "Thettukalil ninnu padikku, anubhavam aanu mahaa guru.", "language": "Malayalam"},
    {"idiom": "ഏഴാം അറിവ് അനുഭവമാണ് (Ezham arivu anubhavamaanu)", "literal_meaning": "Experience is the seventh sense.", "figurative_meaning": "True wisdom comes from personal experience.", "example": "Avarude life lessons kandu padikkanam, ezham arivu anubhavamaanu.", "language": "Malayalam"},
    {"idiom": "കണ്ണുള്ളപ്പോൾ കണ്ണിന്റെ വില അറിയില്ല (Kannullappol kanninte vila ariyilla)", "literal_meaning": "One does not realize the value of eyes while having them.", "figurative_meaning": "People don't appreciate what they have until they lose it.", "example": "Achan ulla kalam aarum anweshichilla, kannullappol kanninte vila ariyilla.", "language": "Malayalam"},
    {"idiom": "പുഴു തിന്നാത്ത പഴം ഇല്ല (Puzhu thinnatha pazham illa)", "literal_meaning": "There is no fruit that hasn't been eaten by a worm.", "figurative_meaning": "No one is completely flawless or perfect.", "example": "Aarum poornaralla, puzhu thinnatha pazham illa.", "language": "Malayalam"},
    {"idiom": "അരയ്ക്കുന്ന കല്ല് പൊടിക്കും (Araykkunna kall podikkum)", "literal_meaning": "The stone that grinds will produce powder.", "figurative_meaning": "Consistent hard work will eventually yield results.", "example": "Nee thudarndu sramikku, araykkunna kall podikkum.", "language": "Malayalam"},
    {"idiom": "അട്ടയെപ്പിടിച്ച് മെത്തയിൽ കിടത്തിയാൽ കിടക്കുമോ (Attayepidichu methayil kidathiyaal kidakkumo)", "literal_meaning": "If you put a leech on a mattress, will it stay there?", "figurative_meaning": "People naturally revert to their own base environments or habits.", "example": "Avanu panam kittiyittum pazhaya swabhavam mattiyailla, attayepidichu methayil kidathiyaal kidakkumo?", "language": "Malayalam"},
    {"idiom": "ആന വായയിൽ അമ്പഴങ്ങ (Aana vayil ampazhanga)", "literal_meaning": "A small fruit in an elephant's mouth.", "figurative_meaning": "An amount that is absurdly too small for a huge need.", "example": "Ee kuranju shabalam kondu kudumbam pottan aavilla, aana vayil ampazhanga poleyanu.", "language": "Malayalam"},

    # Batch 3 Idioms
    {"idiom": "കുരയ്ക്കുന്ന പട്ടി കടിക്കില്ല (Kuraykkunna patti kadikkilla)", "literal_meaning": "A barking dog will not bite.", "figurative_meaning": "People who make a lot of noise or threats rarely take action.", "example": "Avan veruthe vaakkukal parayukayanu, kuraykkunna patti kadikkilla.", "language": "Malayalam"},
    {"idiom": "കനകം മൂലം കാമിനി മൂലം (Kanakam moolam kaamini moolam)", "literal_meaning": "Through gold and through a woman.", "figurative_meaning": "Wealth and women are the root causes of all conflicts in the world.", "example": "Orupadu war nadannathu kanakam moolam kaamini moolam aanu.", "language": "Malayalam"},
    {"idiom": "ആളറിയാതെ ആളെ കൊല്ലരുത് (Aalariyathe aale kollaruthu)", "literal_meaning": "Do not kill a person without knowing them.", "figurative_meaning": "Do not judge or punish someone before knowing the full truth about them.", "example": "Avanude bhagam kelkkuka, aalariyathe aale kollaruthu.", "language": "Malayalam"},
    {"idiom": "കണ്ടതറിയാത്തവൻ കൊണ്ടതറിയും (Kandathariyathavan kondathariyum)", "literal_meaning": "He who doesn't learn by seeing, learns by getting hit.", "figurative_meaning": "Some people only learn their lesson the hard way, through painful experience.", "example": "Avan paranju kettu padikkilla, kandathariyathavan kondathariyum.", "language": "Malayalam"},
    {"idiom": "കാക്കയ്ക്കും കോഴിക്കും കല്ല്യാണം (Kaakkakkum kozhikkum kallyaanam)", "literal_meaning": "A wedding between a crow and a chicken.", "figurative_meaning": "A completely chaotic, mismatched, or absurd situation.", "example": "Aa projectil ellam kuzhapam aanu, kaakkakkum kozhikkum kallyaanam pole.", "language": "Malayalam"},
    {"idiom": "കൈപ്പുള്ളവനേ മധുരത്തിന്റെ വിലയറിയൂ (Kaippullavane madhurathinte vilayariyu)", "literal_meaning": "Only those who have bitterness know the value of sweetness.", "figurative_meaning": "Only those who have suffered know the true value of happiness.", "example": "Daridryam anubhavichavarkke panathinte vila ariyoo, kaippullavane madhurathinte vilayariyu.", "language": "Malayalam"},
    {"idiom": "കാട്ടിലെ തടി തേവരുടെ ആന (Kaattile thadi thevarude aana)", "literal_meaning": "Timber from the forest, elephant belongs to the Lord.", "figurative_meaning": "Carelessly spending or destroying property that belongs to someone else.", "example": "Sarkaar panam avan dhoorthadikkunnu, kaattile thadi thevarude aana pole.", "language": "Malayalam"},
    {"idiom": "ചോദിക്കാൻ ആളില്ലെങ്കിൽ അമ്പലവാസി എന്തും ചെയ്യും (Chodikkan aalillengil ambalavaasi enthum cheyyum)", "literal_meaning": "If no one questions, the temple worker will do anything.", "figurative_meaning": "Without oversight or accountability, people will abuse their power.", "example": "Manager illatha neram avar paniyedukkilla, chodikkan aalillengil ambalavaasi enthum cheyyum.", "language": "Malayalam"},
    {"idiom": "താൻ കുഴിച്ച കുഴിയിൽ താൻ തന്നെ വീഴും (Thaan kuzhicha kuzhiyil thaan thanne veezhum)", "literal_meaning": "You will fall into the pit you dig.", "figurative_meaning": "Karma; if you plot against others, you will ruin yourself.", "example": "Avan vere oralude pani kalayaan sramichu pakshe avante pani poyi, thaan kuzhicha kuzhiyil thaan thanne veezhum.", "language": "Malayalam"},
    {"idiom": "നൂറു വട്ടം അറുത്താലും കൊതുകിന്റെ കാല് (Nooru vattam aruthalum kothukinte kaalu)", "literal_meaning": "Even if cut 100 times, a mosquito's leg remains small.", "figurative_meaning": "Something insignificant will remain insignificant no matter what you do.", "example": "Avanude businessil ethra maattangal varuthiyalum athu valuthaavilla, nooru vattam aruthalum kothukinte kaalu thanne.", "language": "Malayalam"},
    {"idiom": "പുലിവാല് പിടിച്ചതുപോലെ (Pulivaalu pidichathupole)", "literal_meaning": "Like catching a tiger's tail.", "figurative_meaning": "Being caught in a dangerous situation where you can neither hold on nor let go.", "example": "Ee puthiya jobil aake prashnamanu, pulivaalu pidichathupole aayi.", "language": "Malayalam"},
    {"idiom": "വടിയെടുത്തു വാഴ വെട്ടരുത് (Vadiyeduthu vazha vettaruthu)", "literal_meaning": "Do not cut a banana tree with a stick.", "figurative_meaning": "Do not do foolish things; use the right tools for the right job.", "example": "Avan ee periya project oru chinna tool vechu cheyyan sramikkunnu, vadiyeduthu vazha vettaruthu.", "language": "Malayalam"},
    {"idiom": "തല പോയാലും ചിരി മാറില്ല (Thala poyalum chiri maarilla)", "literal_meaning": "Even if the head is cut, the smile won't fade.", "figurative_meaning": "A deeply ingrained habit or characteristic persists until the very end.", "example": "Avan marikkuvolam jhooth parayum, thala poyalum chiri maarilla.", "language": "Malayalam"},
    {"idiom": "പാലം കടക്കുവോളം നാരായണ നാരായണ (Paalam kadakkuvolam Narayana Narayana)", "literal_meaning": "Praying Narayana until crossing the bridge.", "figurative_meaning": "Acting humble and devoted only as long as you are in danger or need help.", "example": "Avashyam theernappol avan enne marannu, paalam kadakkuvolam Narayana Narayana.", "language": "Malayalam"},
    {"idiom": "പത്തായത്തിൽ നെല്ലുണ്ടെങ്കിൽ എലി വയനാട്ടിൽ നിന്നും വരും (Pathayathil nellundengil eli wayanattil ninnum varum)", "literal_meaning": "If there is paddy in the granary, rats will come even from Wayanad.", "figurative_meaning": "If you are wealthy or successful, people will find you no matter where you are.", "example": "Avanu lottery adichappol ellavarum vannu, pathayathil nellundengil eli wayanattil ninnum varumallo.", "language": "Malayalam"},
    {"idiom": "വെള്ളത്തിൽ വരച്ച വര പോലെ (Vellathil varacha vara pole)", "literal_meaning": "Like a line drawn on water.", "figurative_meaning": "Something that disappears instantly; fleeting and impermanent.", "example": "Avarude sneham vellathil varacha vara poleyayi, udane maanju poyi.", "language": "Malayalam"},
    {"idiom": "മാതാവിനേക്കാൾ വലിയ ദൈവമില്ല (Maathavinekkaal valiya daivamilla)", "literal_meaning": "There is no god greater than the mother.", "figurative_meaning": "A mother is the supreme figure of love and reverence.", "example": "Amma parayunnathu kelkkanam, maathavinekkaal valiya daivamilla.", "language": "Malayalam"},
    {"idiom": "കണ്ണടച്ചാൽ ഇരുട്ടാവില്ല (Kannadachal iruttaavilla)", "literal_meaning": "Just because you close your eyes, it doesn't become dark.", "figurative_meaning": "Ignoring a problem does not make it go away.", "example": "Nee sathyam manassilakku, kannadachal iruttaavilla.", "language": "Malayalam"},
    {"idiom": "പെറ്റ തള്ളയ്ക്ക് അറിയാം പിള്ളയുടെ വേദന (Petta thallakku ariyaam pillayude vedana)", "literal_meaning": "Only the mother who gave birth knows the child's pain.", "figurative_meaning": "Only the person intimately involved in a situation truly understands the struggle.", "example": "Nammude prashnam namukke ariyoo, petta thallakku ariyaam pillayude vedana.", "language": "Malayalam"},
    {"idiom": "തേൻ എടുത്തവൻ കൈ നക്കും (Then eduthavan kai nakkum)", "literal_meaning": "He who takes the honey will lick his fingers.", "figurative_meaning": "People managing money or resources will naturally take a small cut for themselves.", "example": "Sarkaar udhyogasthar panam vangi, then eduthavan kai nakkumallo.", "language": "Malayalam"},
    {"idiom": "തലക്കനം വന്നാൽ തറയറിയില്ല (Thalakkanam vannal tharayariyilla)", "literal_meaning": "Arrogance makes you lose touch with the ground.", "figurative_meaning": "When success goes to someone's head, they forget their humble beginnings.", "example": "Avanu ippol nalla ahankaram aanu, thalakkanam vannal tharayariyilla.", "language": "Malayalam"},
    {"idiom": "നാട് ഓടുമ്പോൾ നടുവേ ഓടണം (Naadu odumbol naduve odanam)", "literal_meaning": "When the village runs, you should run in the middle.", "figurative_meaning": "You should adapt to the customs and trends of the society you live in.", "example": "Ivide ellavarum inganeyanu cheyyunnathu, naadu odumbol naduve odanam.", "language": "Malayalam"},
    {"idiom": "വിദ്വാന് എവിടെയും സ്ഥാനം (Vidwanu evideyum sthaanam)", "literal_meaning": "A wise man is respected everywhere.", "figurative_meaning": "Knowledge and talent will bring respect regardless of location.", "example": "Avanude budhi kaaranam avanu eppozhum velayundu, vidwanu evideyum sthaanam.", "language": "Malayalam"},
    {"idiom": "ഇരിക്കുന്ന കൊമ്പ് മുറിക്കരുത് (Irikkunna kombu murikkaruthu)", "literal_meaning": "Do not cut the branch you are sitting on.", "figurative_meaning": "Do not destroy the very thing that supports you.", "example": "Ninne sahayikkunna aale thettikkaruthu, irikkunna kombu murikkaruthu.", "language": "Malayalam"},
    {"idiom": "കൈ വിട്ട ആയുധം പോലെ (Kai vitta aayudham pole)", "literal_meaning": "Like a weapon that has left the hand.", "figurative_meaning": "Words once spoken or actions once taken cannot be reversed.", "example": "Vaakkukal sookshichu parayanam, kai vitta aayudham poleyanu.", "language": "Malayalam"},
    {"idiom": "കാറ്റിനൊത്ത് പായ വിരിക്കുക (Kaattinothu paaya virikkuka)", "literal_meaning": "Sail according to the wind.", "figurative_meaning": "Adapt your actions according to the changing circumstances.", "example": "Market maarunnathinu anusarichu business maattanam, kaattinothu paaya virikkuka.", "language": "Malayalam"},
    {"idiom": "താൻ പാതി ദൈവം പാതി (Thaan paathi daivam paathi)", "literal_meaning": "Man does half, God does half.", "figurative_meaning": "You must put in the effort, and God will take care of the rest.", "example": "Nee padikkuka, baakki deivam nokkikkollum, thaan paathi daivam paathi.", "language": "Malayalam"},
    {"idiom": "പയ്യെ തിന്നാൽ പനയും തിന്നാം (Payye thinnal panayum thinnam)", "literal_meaning": "If you eat slowly, you can even eat a palm tree.", "figurative_meaning": "With patience and perseverance, you can achieve impossible things.", "example": "Ee valiya project padukke theerkkam, payye thinnal panayum thinnam.", "language": "Malayalam"},
    {"idiom": "മോങ്ങാനിരുന്ന നായയുടെ തലയിൽ തേങ്ങ വീണു (Mongaanirunna naayayude thalayil thenga veenu)", "literal_meaning": "A coconut fell on the head of a dog that was already about to howl.", "figurative_meaning": "Providing a ready excuse for someone who was already looking for a reason to complain.", "example": "Avanu officeil pokan madi aayirunnu appozha mazha vannathu, mongaanirunna naayayude thalayil thenga veenu.", "language": "Malayalam"}
]

file_path = 'data/raw/malayalam.json'

data = []
if os.path.exists(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            data = json.load(f)
        except:
            pass

existing_idioms = {item['idiom'].split(' (')[0].strip() for item in data if 'idiom' in item}
filtered_new_idioms = []
for item in new_idioms:
    base_idiom = item['idiom'].split(' (')[0].strip()
    if base_idiom not in existing_idioms:
        filtered_new_idioms.append(item)

data.extend(filtered_new_idioms)

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Added {len(filtered_new_idioms)} new unique idioms to malayalam.json! Total is now {len(data)}.")
