import json
import os

new_idioms = [
    {"idiom": "എലിയെ പേടിച്ച് ഇല്ലം ചുടുക (Eliye pedichu illam chuduka)", "literal_meaning": "Burning the house out of fear of a rat.", "figurative_meaning": "Taking an extreme or destructive measure to solve a small problem.", "example": "Cheruthaaya problem solve cheyyan company thanne adaikkunnathu eliye pedichu illam chudunnathu poleyanu.", "language": "Malayalam"},
    {"idiom": "ഓടുന്ന നായയ്ക്ക് ഒരു മുഴം മുമ്പേ (Odunna naayakku oru muzham mumpe)", "literal_meaning": "Throwing the stick a yard ahead of the running dog.", "figurative_meaning": "Being highly proactive; anticipating actions before they happen.", "example": "Market maarunnathinu munpe avar product maatti, odunna naayakku oru muzham mumpe.", "language": "Malayalam"},
    {"idiom": "കരിമ്പു കാട്ടിൽ ആന കയറിയതു പോലെ (Karimbu kattil aana kayariyathu pole)", "literal_meaning": "Like an elephant entering a sugarcane field.", "figurative_meaning": "Being in a state of absolute joy with unlimited access to what one loves.", "example": "Sweets shopil kayariya kuttiye kandal karimbu kattil aana kayariyathu poleyanu.", "language": "Malayalam"},
    {"idiom": "പട്ടി കുരച്ചാൽ പല്ലക്ക് നിൽക്കുമോ (Patti kurachal pallakku nilkkumo)", "literal_meaning": "Will the palanquin stop if a dog barks?", "figurative_meaning": "The progress of the great will not be stopped by the criticism of the insignificant.", "example": "Avarude parihasangal kettu nee pinmaranda, patti kurachal pallakku nilkkumo.", "language": "Malayalam"},
    {"idiom": "കുറുക്കന്റെ കണ്ണ് കോഴിക്കൂട്ടിൽ (Kurukkante kannu kozhikkoottil)", "literal_meaning": "The fox's eyes are always on the chicken coop.", "figurative_meaning": "A person with ulterior motives always focuses on their target.", "example": "Avan nallathu parayunnundengilum kurukkante kannu kozhikkoottil aanu.", "language": "Malayalam"},
    {"idiom": "തലയിരിക്കുമ്പോൾ വാലാടരുത് (Thalayirikkumbol vaaladaruthu)", "literal_meaning": "The tail shouldn't wag when the head is present.", "figurative_meaning": "Subordinates should not overstep when the leader is present.", "example": "MD ivide ullappol nee theerumanam edukkaruthu, thalayirikkumbol vaaladaruthu.", "language": "Malayalam"},
    {"idiom": "പാല് കുടിച്ച പാമ്പും കടിക്കും (Paalu kudicha paambum kadikkum)", "literal_meaning": "Even a snake fed with milk will bite.", "figurative_meaning": "A wicked person will betray you even if you treat them well.", "example": "Avanodu nannayi perumariyittum chathichu, paalu kudicha paambum kadikkum.", "language": "Malayalam"},
    {"idiom": "മീൻ കുഞ്ഞിനെ നീന്താൻ പഠിപ്പിക്കണോ (Meen kunjine neenthan padippikkano)", "literal_meaning": "Do you need to teach a baby fish how to swim?", "figurative_meaning": "You don't need to teach someone what they are naturally talented at.", "example": "Avanu coding ariyamo ennu chodhikkanda, meen kunjine neenthan padippikkano.", "language": "Malayalam"},
    {"idiom": "ഒരുമയുണ്ടെങ്കിൽ ഉലക്കമേലും കിടക്കാം (Orumayundengil ulakkamelum kidakkam)", "literal_meaning": "If there is unity, you can sleep even on a pestle.", "figurative_meaning": "Any difficult situation is manageable if people stand united.", "example": "Ee prathisandhiyil namukku orumichu nilkkam, orumayundengil ulakkamelum kidakkam.", "language": "Malayalam"},
    {"idiom": "മുങ്ങിച്ചാവാൻ പോകുന്നവൻ കച്ചിത്തുരുമ്പും പിടിക്കും (Mungichavan pokunnavan kachithurumbum pidikkum)", "literal_meaning": "A drowning man will catch even a straw.", "figurative_meaning": "A desperate person will try any small chance to save themselves.", "example": "Avan last chanceum upayogichu, mungichavan pokunnavan kachithurumbum pidikkum.", "language": "Malayalam"},
    {"idiom": "കാക്ക മലർന്നു പറക്കുമോ (Kaakka malarnnu parakkumo)", "literal_meaning": "Will a crow fly upside down?", "figurative_meaning": "Something that is completely impossible.", "example": "Avan enne sahayikkum ennu ne karuthunnuvo, kaakka malarnnu parakkumo?", "language": "Malayalam"},
    {"idiom": "ഉപ്പു തിന്നവൻ വെള്ളം കുടിക്കും (Uppu thinnavan vellam kudikkum)", "literal_meaning": "He who eats salt will drink water.", "figurative_meaning": "You will have to face the consequences of your wrong actions.", "example": "Thettu cheythathu pidikkappettu, uppu thinnavan vellam kudikkum.", "language": "Malayalam"},
    {"idiom": "അണ്ണാറക്കണ്ണനും തന്നാലായത് (Annarakkannanum thannalayathu)", "literal_meaning": "Even a squirrel does what it can.", "figurative_meaning": "Every small contribution matters.", "example": "Enikondu aavunna sahayam njan cheythu, annarakkannanum thannalayathu.", "language": "Malayalam"},
    {"idiom": "വേരറുത്ത മരം പോലെ (Verarutha maram pole)", "literal_meaning": "Like a tree with its roots cut.", "figurative_meaning": "Completely helpless and falling.", "example": "Swaytham business pottiyappol avan verarutha maram pole aayi.", "language": "Malayalam"},
    {"idiom": "മുള്ളു കൊണ്ടു മുള്ളെടുക്കണം (Mullu kondu mulledukkanam)", "literal_meaning": "Remove a thorn using another thorn.", "figurative_meaning": "Fight fire with fire; use a bad thing to cure another bad thing.", "example": "Avanude kallatharam kandupidikkan mullu kondu mulledukkanam.", "language": "Malayalam"},
    {"idiom": "കാറ്റുളളപ്പോൾ പാറ്റണം (Kattullappol pattanam)", "literal_meaning": "Winnow when the wind blows.", "figurative_meaning": "Make hay while the sun shines; seize the opportunity.", "example": "Avasaram ullappol thanne muthalakkuka, kattullappol pattanam.", "language": "Malayalam"},
    {"idiom": "ആശാന് അടുപ്പിലും ആവാം (Aashaanu aduppilum aavam)", "literal_meaning": "The master can even do it in the stove.", "figurative_meaning": "Experts or masters are granted exceptions to the rules.", "example": "Avar rules thettichalum aarum onnum parayilla, aashaanu aduppilum aavam.", "language": "Malayalam"},
    {"idiom": "തിളച്ച വെള്ളത്തിൽ വീണ പൂച്ച പച്ചവെള്ളം കണ്ടാലും പേടിക്കും (Thilacha vellathil veena poocha pachavellam kandalum pedikkum)", "literal_meaning": "A cat that fell in boiling water will fear even cold water.", "figurative_meaning": "Once bitten, twice shy.", "example": "Pazhaya experience kaaranam avan onninum thuniyunnilla, thilacha vellathil veena poocha pole.", "language": "Malayalam"},
    {"idiom": "നനഞ്ഞെടം കുഴിക്കുക (Nananjedam kuzhikkuka)", "literal_meaning": "Digging where it is wet.", "figurative_meaning": "Taking the easy way out; exploiting a vulnerable person.", "example": "Avan ellavarudeyum weakness muthaledukkum, nananjedam kuzhikkuka aanu pathivu.", "language": "Malayalam"},
    {"idiom": "പൊന്നുരുക്കുന്നിടത്ത് പൂച്ചക്കെന്തു കാര്യം (Ponnurukkunnidathu poochakkenthu karyam)", "literal_meaning": "What business does a cat have where gold is melted?", "figurative_meaning": "What business does an ignorant/irrelevant person have in serious matters?", "example": "Valiyavarude meeingil nee enthina varunne, ponnurukkunnidathu poochakkenthu karyam.", "language": "Malayalam"},
    {"idiom": "വാളെടുക്കുന്നവൻ വാളാൽ (Valedukkunnavan valal)", "literal_meaning": "He who lives by the sword dies by the sword.", "figurative_meaning": "Those who commit violence will eventually suffer from it.", "example": "Don aayirunnavan adhe vazhiyil marihcu, valedukkunnavan valal.", "language": "Malayalam"},
    {"idiom": "ശ്വാനന്റെ വാല് പന്തീരാണ്ട് കുഴലിലിട്ടാലും വളഞ്ഞു തന്നെ (Shwanante vaalu pantheerandu kuzhalilittalum valanju thanne)", "literal_meaning": "A dog's tail put in a pipe for 12 years remains crooked.", "figurative_meaning": "You cannot change the fundamental bad nature of a person.", "example": "Avanu ethra upadesham koduthalum maarilla, shwanante vaalu kuzhalilittathu pole.", "language": "Malayalam"},
    {"idiom": "ചക്കിക്കൊത്ത ചങ്കരൻ (Chakkikkotha Chankaran)", "literal_meaning": "Chankaran is the perfect match for Chakki.", "figurative_meaning": "Made for each other, usually used for two similarly flawed people.", "example": "Avar randum kudi orumichu thettukal cheyyunnu, chakkikkotha chankaran.", "language": "Malayalam"},
    {"idiom": "ഇരുന്നിട്ടു വേണം കാലു നീട്ടാൻ (Irunnittu venam kaalu neettan)", "literal_meaning": "Sit first before stretching your legs.", "figurative_meaning": "Secure your position before demanding more or acting arrogant.", "example": "Job sthiramavunnathinu munpe avarodu demand cheyyaruthu, irunnittu venam kaalu neettan.", "language": "Malayalam"},
    {"idiom": "കുളക്കോഴിക്ക് എന്ത് കുളിക്കടവ് (Kulakkozhikku enthu kulikkadavu)", "literal_meaning": "What is a bathing step to a water hen?", "figurative_meaning": "A person who is always wandering has no fixed home or boundaries.", "example": "Nirantharam yathra cheyyunna avanu sthiramayi oridathu nilkkan aavilla, kulakkozhikku enthu kulikkadavu.", "language": "Malayalam"},
    {"idiom": "വെളുക്കാൻ തേച്ചത് പാണ്ടായി (Velukkan thechathu paandaayi)", "literal_meaning": "An attempt to beautify resulted in vitiligo.", "figurative_meaning": "An attempt to improve a situation made it disastrously worse.", "example": "System nannakkan sramichathu aake crash aayi, velukkan thechathu paandaayi.", "language": "Malayalam"},
    {"idiom": "അൽപ്പന് അർത്ഥം കിട്ടിയാൽ അർദ്ധരാത്രിക്ക് കുട പിടിക്കും (Alpanu artham kittiyal ardharathrikku kuda pidikkum)", "literal_meaning": "If a mean person gets wealth, he will hold an umbrella at midnight.", "figurative_meaning": "When an undeserving person gets sudden wealth, they show off foolishly.", "example": "Lottery adichappol avante ahankaram kandille, alpanu artham kittiyal ardharathrikku kuda pidikkum.", "language": "Malayalam"},
    {"idiom": "ഉറുമ്പിനും തന്റെ ജീവൻ വലുതാണ് (Urumbinum thante jeevan valuthaanu)", "literal_meaning": "Even an ant values its life.", "figurative_meaning": "Every living being values its own existence, no matter how small.", "example": "Aareyum drohikkaruthu, urumbinum thante jeevan valuthaanu.", "language": "Malayalam"},
    {"idiom": "കാണം വിറ്റും ഓണം ഉണ്ണണം (Kaanam vittum Onam unnanam)", "literal_meaning": "Celebrate Onam even if you have to sell your property.", "figurative_meaning": "Festivals or traditions must be kept alive even at great personal cost.", "example": "Bhudhimuttundengilum onam aaghoshikkanam, kaanam vittum onam unnanamennalle.", "language": "Malayalam"},
    {"idiom": "ചുട്ടു തിന്നാലും വാസന പോവില്ല (Chuttu thinnalum vaasana povilla)", "literal_meaning": "Even if roasted, the smell won't go.", "figurative_meaning": "Deep-rooted bad habits cannot be eradicated easily.", "example": "Avanude kalla swabhavam maarilla, chuttu thinnalum vaasana povilla.", "language": "Malayalam"},
    {"idiom": "പുര കത്തുമ്പോൾ വാഴ വെട്ടുക (Pura kathumbol vazha vettuka)", "literal_meaning": "Cutting the banana tree while the house is burning.", "figurative_meaning": "Selfishly taking advantage of someone else's disaster.", "example": "Nattil prashnam nadakkumbol avar swantham karyam nokkunnu, pura kathumbol vazha vettukayanu.", "language": "Malayalam"},
    {"idiom": "അടി തെറ്റിയാൽ ആനയും വീഴും (Adi thettiyaal aaneyum veezhum)", "literal_meaning": "Even an elephant will fall if it takes a wrong step.", "figurative_meaning": "Even the strongest or most experienced person can fail if they are careless.", "example": "Avan ethra valiya expert aayalum sradhikkanam, adi thettiyal aaneyum veezhum.", "language": "Malayalam"},
    {"idiom": "അക്കരെ നിൽക്കുമ്പോൾ ഇക്കരെ പച്ച (Akkare nilkkumpol ikkare pacha)", "literal_meaning": "Things look green on this shore from the other shore.", "figurative_meaning": "The grass is always greener on the other side.", "example": "Avanu purathu pokan ishtamanu, pakshe akkare nilkkumpol ikkare pacha aanu.", "language": "Malayalam"},
    {"idiom": "അനുഭവം ആണ് മഹാ ഗുരു (Anubhavam aanu mahaa guru)", "literal_meaning": "Experience is the great teacher.", "figurative_meaning": "You learn the best lessons from your own experiences.", "example": "Thettukalil ninnu padikku, anubhavam aanu mahaa guru.", "language": "Malayalam"},
    {"idiom": "ഏഴാം അറിവ് അനുഭവമാണ് (Ezham arivu anubhavamaanu)", "literal_meaning": "Experience is the seventh sense.", "figurative_meaning": "True wisdom comes from personal experience.", "example": "Avarude life lessons kandu padikkanam, ezham arivu anubhavamaanu.", "language": "Malayalam"},
    {"idiom": "കണ്ണുള്ളപ്പോൾ കണ്ണിന്റെ വില അറിയില്ല (Kannullappol kanninte vila ariyilla)", "literal_meaning": "One does not realize the value of eyes while having them.", "figurative_meaning": "People don't appreciate what they have until they lose it.", "example": "Achan ulla kalam aarum anweshichilla, kannullappol kanninte vila ariyilla.", "language": "Malayalam"},
    {"idiom": "പുഴു തിന്നാത്ത പഴം ഇല്ല (Puzhu thinnatha pazham illa)", "literal_meaning": "There is no fruit that hasn't been eaten by a worm.", "figurative_meaning": "No one is completely flawless or perfect.", "example": "Aarum poornaralla, puzhu thinnatha pazham illa.", "language": "Malayalam"},
    {"idiom": "അരയ്ക്കുന്ന കല്ല് പൊടിക്കും (Araykkunna kall podikkum)", "literal_meaning": "The stone that grinds will produce powder.", "figurative_meaning": "Consistent hard work will eventually yield results.", "example": "Nee thudarndu sramikku, araykkunna kall podikkum.", "language": "Malayalam"},
    {"idiom": "അട്ടയെപ്പിടിച്ച് മെത്തയിൽ കിടത്തിയാൽ കിടക്കുമോ (Attayepidichu methayil kidathiyaal kidakkumo)", "literal_meaning": "If you put a leech on a mattress, will it stay there?", "figurative_meaning": "People naturally revert to their own base environments or habits.", "example": "Avanu panam kittiyittum pazhaya swabhavam mattiyailla, attayepidichu methayil kidathiyaal kidakkumo?", "language": "Malayalam"},
    {"idiom": "ആന വായയിൽ അമ്പഴങ്ങ (Aana vayil ampazhanga)", "literal_meaning": "A small fruit in an elephant's mouth.", "figurative_meaning": "An amount that is absurdly too small for a huge need.", "example": "Ee kuranju shabalam kondu kudumbam pottan aavilla, aana vayil ampazhanga poleyanu.", "language": "Malayalam"}
]

file_path = 'data/raw/malayalam.json'

data = []
if os.path.exists(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            data = json.load(f)
        except:
            pass

existing_idioms = {item['idiom'].split(' (')[0].strip() for item in data if 'idiom' in item}
filtered_new_idioms = []
for item in new_idioms:
    base_idiom = item['idiom'].split(' (')[0].strip()
    if base_idiom not in existing_idioms:
        filtered_new_idioms.append(item)

data.extend(filtered_new_idioms)

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Added {len(filtered_new_idioms)} new unique idioms to malayalam.json! Total is now {len(data)}.")
