import json
import os

new_idioms = [
    {"idiom": "కుక్క తోక వంకర (Kukka thoka vankara)", "literal_meaning": "A dog's tail is crooked.", "figurative_meaning": "Old habits die hard; a person's basic nature cannot be changed easily.", "example": "Vaadu maradu, kukka thoka vankara.", "language": "Telugu"},
    {"idiom": "అందని ద్రాక్ష పండ్లు పుల్లన (Andani draksha pandlu pullana)", "literal_meaning": "Unreachable grapes are sour.", "figurative_meaning": "Disparaging what you cannot achieve; sour grapes.", "example": "Job raakapothe company baaledannadu, andani draksha pandlu pullana.", "language": "Telugu"},
    {"idiom": "చేతులు కాలాక ఆకులు పట్టుకున్నట్లు (Chetulu kalaka aakulu pattukunnatlu)", "literal_meaning": "Holding leaves after the hands are burnt.", "figurative_meaning": "Crying over spilt milk; taking precautions when it is too late.", "example": "Exam fail ayyaka chadavadam chetulu kalaka aakulu pattukunnatlu.", "language": "Telugu"},
    {"idiom": "కాకి పిల్ల కాకికి ముద్దు (Kaaki pilla kaakiki muddu)", "literal_meaning": "A crow's child is beautiful to the crow.", "figurative_meaning": "Everyone loves their own offspring, regardless of their flaws.", "example": "Vaadu em chesina valla ammaku nacchuthundi, kaaki pilla kaakiki muddu.", "language": "Telugu"},
    {"idiom": "పిట్ట కొంచెం కూత ఘనం (Pitta koncham kootha ghanam)", "literal_meaning": "Small bird, loud song.", "figurative_meaning": "Small in size or status but making a big impact or loud noise.", "example": "Vaadu chinnavaadaina goppa pani chesadu, pitta koncham kootha ghanam.", "language": "Telugu"},
    {"idiom": "పులిని చూసి నక్క వాతలు పెట్టుకున్నట్లు (Pulini chusi nakka vathalu pettukunnatlu)", "literal_meaning": "Fox branding itself after seeing a tiger.", "figurative_meaning": "Foolishly imitating someone greater and hurting oneself.", "example": "Vaadini chusi nuvvu appu cheyaku, pulini chusi nakka vathalu pettukunnatlu avuthundi.", "language": "Telugu"},
    {"idiom": "అడవిలో కాచిన వెన్నెల (Adavilo kaachina vennela)", "literal_meaning": "Moonlight in the forest.", "figurative_meaning": "Wasted effort or beauty that goes unappreciated.", "example": "Ee project gurinchi evariki theliyaledu, adavilo kaachina vennela aindi.", "language": "Telugu"},
    {"idiom": "రొట్టె విరిగి నేతిలో పడ్డట్టు (Rotte virigi nethilo paddattu)", "literal_meaning": "Bread breaking and falling into ghee.", "figurative_meaning": "A completely unexpected stroke of good luck.", "example": "Job pothe inka manchi job vachindi, rotte virigi nethilo paddattu.", "language": "Telugu"},
    {"idiom": "గాలిలో దీపం పెట్టి దేవుడా అన్నట్లు (Gaalilo deepam petti devuda annatlu)", "literal_meaning": "Keeping a lamp in the wind and calling God.", "figurative_meaning": "Acting carelessly and hoping for a miracle.", "example": "Chadavakunda pass avvali anukovadam gaalilo deepam petti devuda annatlu.", "language": "Telugu"},
    {"idiom": "ఏ ఎండకు ఆ గొడుగు (Ye endaku aa godugu)", "literal_meaning": "An umbrella for the respective sun.", "figurative_meaning": "Adapting to situations for personal benefit; being an opportunist.", "example": "Vaadu ye endaku aa godugu padathadu, nammakam ledu.", "language": "Telugu"},
    {"idiom": "నిండు కుండ తొణకదు (Nindu kunda thonakadu)", "literal_meaning": "A full pot doesn't spill.", "figurative_meaning": "A truly wise and knowledgeable person is calm and doesn't show off.", "example": "Aayana entha goppavadaina garvam ledu, nindu kunda thonakadu.", "language": "Telugu"},
    {"idiom": "గోరంత దాన్ని కొండంత చేయడం (Goranta daanni kondanta cheyadam)", "literal_meaning": "Making a fingernail-sized thing into a mountain.", "figurative_meaning": "Making a mountain out of a molehill; exaggerating a small issue.", "example": "Chinna godavani goranta daanni kondanta chesaru.", "language": "Telugu"},
    {"idiom": "చెవిటి వాడి ముందు శంఖం ఊదినట్లు (Cheviti vaadi mundu shankham oodinatlu)", "literal_meaning": "Blowing a conch in front of a deaf person.", "figurative_meaning": "Wasting words on someone who refuses to listen or understand.", "example": "Vaadiki advice ivvadam cheviti vaadi mundu shankham oodinatlu.", "language": "Telugu"},
    {"idiom": "గుడ్డి కన్నా మెల్ల మేలు (Guddi kanna mella melu)", "literal_meaning": "A squint is better than blindness.", "figurative_meaning": "Something is better than nothing.", "example": "Asalu job lekapovadam kante chinna job raavadam guddi kanna mella melu.", "language": "Telugu"},
    {"idiom": "చంకలో పిల్లిని పెట్టుకొని ఊరంతా వెతికినట్లు (Chankalo pillini pettukoni oorantha vethikinatlu)", "literal_meaning": "Keeping a cat in the armpit and searching the whole town.", "figurative_meaning": "Searching everywhere for something that is right in front of you.", "example": "Pen chethilone pettukoni chankalo pillini pettukoni oorantha vethikinatlu vethukuthunnava?", "language": "Telugu"},
    {"idiom": "పిల్లి కళ్ళు మూసుకుని పాలు తాగుతూ... (Pilli kallu musukuni paalu thaguthu...)", "literal_meaning": "A cat drinks milk with its eyes closed thinking no one sees.", "figurative_meaning": "Doing something wrong secretly, foolishly believing no one notices.", "example": "Nuvvu chese thappulu andarikii thelusu, pilli kallu musukuni paalu thaguthunnanukoku.", "language": "Telugu"},
    {"idiom": "గురువింద గింజ తన నలుపు ఎరుగదు (Guruvinda ginja thana nalupu erugadu)", "literal_meaning": "The guruvinda seed doesn't know its own blackness.", "figurative_meaning": "A person ignoring their own faults while criticizing others.", "example": "Vaadu eppudu itarulanu vimarsisthadu, guruvinda ginja thana nalupu erugadu.", "language": "Telugu"},
    {"idiom": "కూసే గాడిద మేసే గాడిదని చెడగొట్టినట్లు (Koose gaadida mese gaadidani chedagottinatlu)", "literal_meaning": "A braying donkey ruined the grazing donkey.", "figurative_meaning": "Bad company corrupts good character.", "example": "Vaadi thoti thirigi veedu kuda chedipoyadu, koose gaadida mese gaadidani chedagottinatlu.", "language": "Telugu"},
    {"idiom": "తల ప్రాణం తోకకు వచ్చినట్లు (Thala pranam thokaku vachinatlu)", "literal_meaning": "Life coming from the head to the tail.", "figurative_meaning": "Facing extreme hardship or fear.", "example": "Aa project complete cheselopu thala pranam thokaku vachindi.", "language": "Telugu"},
    {"idiom": "మింగ మెతుకు లేదు, మీసాలకు సంపెంగ నూనె (Minga methuku ledu, meesalaku sampenga nune)", "literal_meaning": "No grain to swallow, but jasmine oil for the mustache.", "figurative_meaning": "Showing off outwardly despite extreme inner poverty or lack of substance.", "example": "Pocket lo rupayi ledu gani branded battalu, minga methuku ledu meesalaku sampenga nune.", "language": "Telugu"},
    {"idiom": "దొంగలు పడ్డ ఆరు నెలలకు కుక్కలు మొరిగినట్లు (Dongalu padda aaru nelalaku kukkalu moriginatlu)", "literal_meaning": "Dogs barking 6 months after the robbery.", "figurative_meaning": "Reacting far too late to a situation to be of any use.", "example": "Incident ayina chaala rojula tharvatha respond avvadam dongalu padda aaru nelalaku kukkalu moriginatlu.", "language": "Telugu"},
    {"idiom": "నోరు మంచిదైతే ఊరు మంచిదవుతుంది (Noru manchidaite ooru manchidavutundi)", "literal_meaning": "If the mouth is good, the town is good.", "figurative_meaning": "If you speak politely, everyone will be good to you.", "example": "Andarito kalupugoluga undu, noru manchidaite ooru manchidavutundi.", "language": "Telugu"},
    {"idiom": "ఆవు చేలో మేస్తే దూడ గట్టున మేస్తుందా (Aavu chelo meste, duda gattuna mestunda)", "literal_meaning": "If the cow grazes in the field, will the calf graze on the edge?", "figurative_meaning": "Like father, like son; children imitate their parents.", "example": "Thandri dongathananalu chestunte koduku kooda alage untadu, aavu chelo meste duda gattuna mestunda.", "language": "Telugu"},
    {"idiom": "కుడితిలో పడ్డ ఎలుక లాగా (Kuditilo padda eluka laaga)", "literal_meaning": "Like a rat fallen in rice wash.", "figurative_meaning": "Being stuck in a messy dilemma unable to get out.", "example": "Rendu offers vachi etu vellalo theliyaka kuditilo padda eluka laaga unnadu.", "language": "Telugu"},
    {"idiom": "తాంబూలాలిచ్చేశాను తన్నుకు చావండి (Thamboolalichhesanu thannuku chavandi)", "literal_meaning": "I gave the betel leaves, now fight to death.", "figurative_meaning": "Washing one's hands of all responsibility and letting others deal with the mess.", "example": "Nenu rules cheppesanu, thamboolalichhesanu thannuku chavandi.", "language": "Telugu"},
    {"idiom": "కంచే చేను మేసినట్లు (Kanche chenu mesinatlu)", "literal_meaning": "The fence grazing the crop.", "figurative_meaning": "The protector turning into the predator.", "example": "Police ye donga ayithe kanche chenu mesinatlu.", "language": "Telugu"},
    {"idiom": "అత్త మీద కోపం దుత్త మీద చూపినట్లు (Attha meeda kopam duttha meeda chupinatlu)", "literal_meaning": "Showing anger towards the mother-in-law on the pot.", "figurative_meaning": "Displaced anger; taking out frustration on innocent people or objects.", "example": "Boss meeda kopam wife meeda chupinchadu, attha meeda kopam duttha meeda chupinatlu.", "language": "Telugu"},
    {"idiom": "దూరపు కొండలు నునుపు (Doorapu kondalu nunupu)", "literal_meaning": "Distant mountains are smooth.", "figurative_meaning": "The grass is always greener on the other side.", "example": "Vere desham vellali anukuntunnadu, doorapu kondalu nunupu kadha.", "language": "Telugu"},
    {"idiom": "నీటిలో రాతలు (Neetilo raathalu)", "literal_meaning": "Writings on water.", "figurative_meaning": "Something that is fleeting, impermanent, or useless.", "example": "Vaadi matalu neetilo raathalu, eppudu maripothadu.", "language": "Telugu"},
    {"idiom": "కప్పకు పుండు వస్తే పాము తల దడిమినట్లు (Kappaku pundu vaste paamu thala dadiminatlu)", "literal_meaning": "Snake massaging a frog's wound.", "figurative_meaning": "Hypocritical help from an enemy who actually intends to harm you.", "example": "Vaadu saayam chestunnanu antunnadu jagratha, kappaku pundu vaste paamu thala dadiminatlu.", "language": "Telugu"},
    {"idiom": "పెదవి దాటితే పెన్న దాటుతుంది (Pedavi daatithe penna daatuthundi)", "literal_meaning": "If it crosses the lip, it crosses the Penna river.", "figurative_meaning": "A secret once spoken spreads uncontrollably and widely.", "example": "Evarkii cheppaku, pedavi daatithe penna daatuthundi.", "language": "Telugu"},
    {"idiom": "దీపం ఉండగానే ఇల్లు చక్కబెట్టుకోవాలి (Deepam undagane illu chakkabettukovali)", "literal_meaning": "Set the house in order while the lamp is burning.", "figurative_meaning": "Make hay while the sun shines; utilize opportunities while they last.", "example": "Vayasu unnapude sampaadinchukovali, deepam undagane illu chakkabettukovali.", "language": "Telugu"},
    {"idiom": "కొత్త బిచ్చగాడు పొద్దెరగడు (Kottha bicchagadu podderagadu)", "literal_meaning": "A new beggar doesn't know the time of day.", "figurative_meaning": "A novice lacks a sense of timing or etiquette in their new role.", "example": "Vaadiki job kothaga vachindi over chestunnadu, kottha bicchagadu podderagadu.", "language": "Telugu"},
    {"idiom": "ఉరుము ఉరుమి మంగలం మీద పడ్డట్టు (Urumu urumi mangalam meeda paddattu)", "literal_meaning": "Thunder rolling and falling on the earthen pan.", "figurative_meaning": "A huge buildup that results in a minor or pathetic outcome.", "example": "Pedda meeting petti chivariki emi cheppaledu, urumu urumi mangalam meeda paddattu.", "language": "Telugu"},
    {"idiom": "బొగ్గులు కడిగితే పాలు అవుతాయా (Boggulu kadigithe paalu avuthaya)", "literal_meaning": "If you wash coal, will it become milk?", "figurative_meaning": "You cannot change someone's inherent bad nature.", "example": "Vaadini entha marchalani chusina labham ledu, boggulu kadigithe paalu avuthaya?", "language": "Telugu"},
    {"idiom": "తాడి చెట్టు ఎక్కే వాడిని ఎంత వరకు ఎగదోయాలి (Thaadi chettu ekke vaadini entha varaku egadoyali)", "literal_meaning": "How far can you push up someone climbing a palm tree?", "figurative_meaning": "You can only help someone so much; eventually, they must do the work themselves.", "example": "Nenu sagam saayam chesanu, thaadi chettu ekke vaadini entha varaku egadoyali?", "language": "Telugu"},
    {"idiom": "శివుని ఆజ్ఞ లేనిదే చీమైనా కుట్టదు (Shivuni aagna lenide cheemaina kuttadu)", "literal_meaning": "Even an ant won't bite without Lord Shiva's command.", "figurative_meaning": "Everything happens according to the will of God.", "example": "Manam entha badhapaddina jarigede jaruguthundi, shivuni aagna lenide cheemaina kuttadu.", "language": "Telugu"},
    {"idiom": "తన కోపమే తన శత్రువు (Thana kopame thana shatruvu)", "literal_meaning": "One's anger is one's enemy.", "figurative_meaning": "Anger only destroys the person who is angry.", "example": "Kopam tagginchuko, thana kopame thana shatruvu.", "language": "Telugu"},
    {"idiom": "పాము చావకూడదు, కర్ర విరగకూడదు (Paamu chavakudadu, karra viragakudadu)", "literal_meaning": "The snake shouldn't die, the stick shouldn't break.", "figurative_meaning": "Resolving a conflict safely without causing harm to either side.", "example": "Godava peddadavvakunda paamu chavakudadu karra viragakudadu anattu problem solve chey.", "language": "Telugu"},
    {"idiom": "పేరు గొప్ప ఊరు దిబ్బ (Peru goppa ooru dibba)", "literal_meaning": "Great name, but the town is a dump.", "figurative_meaning": "Famous in name but lacking in actual substance.", "example": "Aa college peru matrame goppa, lopala emi ledu, peru goppa ooru dibba.", "language": "Telugu"},
    {"idiom": "మూలిగే నక్క మీద తాటికాయ పడ్డట్టు (Moolige nakka meeda thaatikaya paddattu)", "literal_meaning": "A palm fruit falling on a groaning fox.", "figurative_meaning": "A sudden disaster striking someone already suffering.", "example": "Appultho unna vaadiki accident ayindi, moolige nakka meeda thaatikaya paddattu.", "language": "Telugu"},
    {"idiom": "రాత్రి అయితే గానీ రంగులు తెలియవు (Rathri ayithe gaani rangulu theliyavu)", "literal_meaning": "Colors aren't known until night falls.", "figurative_meaning": "True colors or difficulties are only revealed during tough times.", "example": "Kastam vasthene evaru elantivaro thelustundi, rathri ayithe gaani rangulu theliyavu.", "language": "Telugu"},
    {"idiom": "ఏకు మేకై కూర్చున్నట్లు (Eku mekai kurchunnatlu)", "literal_meaning": "A cotton wick becoming a nail.", "figurative_meaning": "Something insignificant becoming a huge nuisance or threat over time.", "example": "Chinna appu eku mekai kurchundi.", "language": "Telugu"},
    {"idiom": "ఉపకారికి అపకారం చేయడం (Upakariki apakaram cheyadam)", "literal_meaning": "Doing harm to the benefactor.", "figurative_meaning": "Biting the hand that feeds you.", "example": "Ninnu nammina vaarini mosam cheyaku, upakariki apakaram cheyadam papam.", "language": "Telugu"}
]

file_path = 'data/raw/telugu.json'
data = []
if os.path.exists(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            data = json.load(f)
        except:
            pass

existing_idioms = {item['idiom'].split(' (')[0].strip() for item in data if 'idiom' in item}
filtered = [item for item in new_idioms if item['idiom'].split(' (')[0].strip() not in existing_idioms]

data.extend(filtered)

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Added {len(filtered)} new unique idioms to telugu.json! Total is now {len(data)}.")
